CREATE DATABASE carros;
USE carros;

CREATE TABLE marcas (
	id INT NOT NULL AUTO_INCREMENT,
	NOME_MARCA VARCHAR(100) NOT NULL,
	ORIGEM VARCHAR(100) NOT NULL,
	PRIMARY KEY (id)
);

CREATE TABLE inventario (
	id INT NOT NULL AUTO_INCREMENT,
	MODELO_CARRO VARCHAR(100) NOT NULL,
	TRANSMISSAO VARCHAR(100) NOT NULL,
	MOTOR VARCHAR(100) NOT NULL,
	COMBUSTIVEL VARCHAR(100) NOT NULL,
	ID_MARCAS INT NOT NULL,
	PRIMARY KEY (id),
	FOREIGN KEY (ID_MARCAS) REFERENCES marcas(id)
);

CREATE TABLE clientes (
	id INT NOT NULL AUTO_INCREMENT,
	NOME VARCHAR(250) NOT NULL,
	SOBRENOME VARCHAR(250) NOT NULL,
	ENDERECO VARCHAR(250) NOT NULL,
	PRIMARY KEY (id)
);
